### ISSUE TITLE
Crash screen graphic uncoloured

### ISSUE THREAD

**Issue by pointydev** [NYRI4/Discolored#19]
Found this on my travels, thought it'd appreciate a little colour.

`https://discord.com/assets/72eaa596042042be6259.svg`
[![graphic](https://canary.discord.com/assets/72eaa596042042be6259.svg)](https://discord.com/assets/72eaa596042042be6259.svg)
![example](https://the.yog.zone/52FBQfD.png)

Thanks,
pointy

**Comment by pointydev** [comment]
Probably to do with the fact that tons of class names just got changed, and not actually a missing asset.

**Comment by BySwiizen** [comment]
Same problem.
