### ISSUE TITLE
"Pictures" don't work

### ISSUE THREAD

**Issue by muuuw** [NYRI4/Discolored#6]
Hello,
the "Pictures" asset in the "Connections" tab of Discord is no longer defined because the name of the original has been changed ... so here are the new ones:

```
/* 🖼️ Pictures */
[style*='background-image: url("/assets/65c84ff0161c0f951f99b035170afb1e.svg");'],
[style*='background-image: url("/assets/caefee6eec712590e489b96139423f9f.svg");'] {
    background-image: url("https://nyri4.github.io/Discolored/assets/pictures.svg") !important;
}
```

Have a good day!

**Comment by muuuw** [comment]
Oh! and I forgot to say it but your work is beautiful! :D

**Comment by muuuw** [comment]
Oh! I forgot to say it but your work is beautiful! :D

**Comment by NYRI4** [comment]
This should be better now, refresh your client and tell me about it :3

**Comment by muuuw** [comment]
Yes, It's perfect! :D
Thank you <3

**Comment by NYRI4** [comment]
Cool, glad you like it !
